# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 105bcf5f6c9f0bb8dc99918f776aa4552e3beb2dd7a1d0b40f5db47107760afad1cab7c3b4fd636c36f00a1d34642b95a9e4806ece20ab68cbeb1a619c0b32a8

test:
  secret_key_base: 9935e162160fb1c64c2f738321aab2c80fd2aacd3239d551cdce4d853a71c9ad82d809f2ac021ab50280ff6eecce6ad08b597fc05942831b82ff36d0cc8b2a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
